version: '3.3'


services: 
  db:
    container_name: mysql-db
    image: mysql
    ports:
      - ${DATABASE_PORT:-4050}:3306
    environment: 
      # change in production !!!
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-example}
      MYSQL_DATABASE: ${DATABASE_NAME:-simple}
    volumes: 
      - data:/var/lib/mysql

  cache:
    container_name: mongo-cache
    image: mongo
    ports: 
      - ${MONGO_PORT:-27017}:27017
    command: --wiredTigerCacheSizeGB ${MONGO_CACHE_SIZE:-0.5}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    volumes: 
    - cache:/data/db

volumes: 
  data:
  cache:



