version: '3.3'


services: 
  db:
    container_name: mysql-db
    image: mysql
    ports:
      - 4050:3306
    environment: 
      MYSQL_ROOT_PASSWORD: omnitron4105_
      MYSQL_DATABASE: simple
      MYSQL_USER: root
      MYSQL_PASSWORD: omnitron4105_
    volumes: 
      - data:/var/lib/mysql

  cache:
    container_name: mongo-cache
    image: mongo
    ports: 
      - 27017:27017
    command: --wiredTigerCacheSizeGB 0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
    - cache:/data/db

volumes: 
  data:
  cache:



